###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'release/**'
      - 'hotfix/**'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3.11.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
          MULTI_STATUS: true
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_CSHARP: true
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_JSX: true
          VALIDATE_MD: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_POWERSHELL: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_SQL: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          # VALIDATE_YAML: true # this currently crashes
          # VALIDATE_EDITORCONFIG: true # really want this on though
          #VALIDATE_ANSIBLE: false
          #VALIDATE_ARM: false
          #VALIDATE_BASH_EXEC: false
          #VALIDATE_CLOJURE: false
          #VALIDATE_CLOUDFORMATION: false
          #VALIDATE_COFFEE: false
          #VALIDATE_DART: false
          #VALIDATE_ENV: false
          #VALIDATE_GO: false
          #VALIDATE_GROOVY: false
          #VALIDATE_JAVA: false
          #VALIDATE_KOTLIN: false
          #VALIDATE_KUBERNETES_KUBEVAL: false
          #VALIDATE_LATEX: false
          #VALIDATE_LUA: false
          #VALIDATE_OPENAPI: false
          #VALIDATE_PERL: false
          #VALIDATE_PHP: false
          #VALIDATE_PHP_BUILTIN: false
          #VALIDATE_PHP_PHPCS: false
          #VALIDATE_PHP_PHPSTAN: false
          #VALIDATE_PHP_PSALM: false
          #VALIDATE_PROTOBUF: false
          #VALIDATE_R: false
          #VALIDATE_RAKU: false
          #VALIDATE_RUBY: false
          #VALIDATE_SNAKEMAKE_LINT: false
          #VALIDATE_SNAKEMAKE_SNAKEFMT: false
          #VALIDATE_STATES: false
          #VALIDATE_TERRAFORM: false
          #VALIDATE_TERRAFORM_TERRASCAN: false
          