name: Auto PR Creation
on:
  push:
    branches-ignore:
    - master
    - "release/**"
    - "hotfix/**"
    - "feature/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: jwalton/gh-find-current-pr@v1.2.0
      id: findPr

    - if: ${{ steps.findPr.outputs.number == '' }}
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1

    - if: ${{ steps.findPr.outputs.number != '' }}
      run: |
        echo "Pull request already exists with id: ${{ steps.findPr.outputs.number }}"
        echo "URL: https://github.com/${{github.repository}}/pull/${{ steps.findPr.outputs.number }}"

    - if: ${{ steps.findPr.outputs.number == '' }}
      id: pr-template
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/PULL_REQUEST_TEMPLATE.md

    - if: ${{ steps.findPr.outputs.number == '' }}
      run: |
        echo COMMIT_MSG=`git log -1 --pretty=%B` >> $GITHUB_ENV

    - if: ${{ steps.findPr.outputs.number == '' }}
      uses: repo-sync/pull-request@v2.6
      with:
        source_branch: ""                     # If blank, default: triggered branch
        destination_branch: "master"          # If blank, default: master
        pr_assignee: "${{ github.actor }}"    # Comma-separated list (no spaces)
        pr_label: "auto-pr"                   # Comma-separated list (no spaces)
        pr_draft: true                        # Creates pull request as draft
        pr_title: "${{ env.COMMIT_MSG }}"
        pr_body: "${{ steps.pr-template.outputs.content }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
